export const NEWS_ITEMS = [
  {
    id: "community",
    imageKey: "community",
    imageAltKey: "HOME_NEWS_COMMUNITY_IMAGE_ALT",
    categoryKey: "HOME_NEWS_COMMUNITY_CATEGORY",
    dateKey: "HOME_NEWS_COMMUNITY_DATE",
    titleKey: "HOME_NEWS_COMMUNITY_TITLE",
    descriptionKey: "HOME_NEWS_COMMUNITY_DESCRIPTION",
    href: "/news",
  },
  {
    id: "culture",
    imageKey: "culture",
    imageAltKey: "HOME_NEWS_CULTURE_IMAGE_ALT",
    categoryKey: "HOME_NEWS_CULTURE_CATEGORY",
    dateKey: "HOME_NEWS_CULTURE_DATE",
    titleKey: "HOME_NEWS_CULTURE_TITLE",
    descriptionKey: "HOME_NEWS_CULTURE_DESCRIPTION",
    href: "/news",
  },
  {
    id: "development",
    imageKey: "development",
    imageAltKey: "HOME_NEWS_DEVELOPMENT_IMAGE_ALT",
    categoryKey: "HOME_NEWS_DEVELOPMENT_CATEGORY",
    dateKey: "HOME_NEWS_DEVELOPMENT_DATE",
    titleKey: "HOME_NEWS_DEVELOPMENT_TITLE",
    descriptionKey: "HOME_NEWS_DEVELOPMENT_DESCRIPTION",
    href: "/news",
  },
  {
    id: "governance",
    imageKey: "governance",
    imageAltKey: "HOME_NEWS_GOVERNANCE_IMAGE_ALT",
    categoryKey: "HOME_NEWS_GOVERNANCE_CATEGORY",
    dateKey: "HOME_NEWS_GOVERNANCE_DATE",
    titleKey: "HOME_NEWS_GOVERNANCE_TITLE",
    descriptionKey: "HOME_NEWS_GOVERNANCE_DESCRIPTION",
    href: "/news",
  },
] as const;